title: <p align="center"> Gautam KK </p>
logo: Gautam KK.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I am woeking in TCS as a Java developer for two years.
  <br>
  </p>



theme: jekyll-theme-minimal
